services:
  perception_container:
    image: probe_perception:latest
    container_name: perception_container
    runtime: nvidia
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm:rw
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    command: -c "source /opt/ros/jazzy/setup.bash && source /ros2_ws/install/setup.bash && ros2 run probe_perception detect_probe.py"