services:
  perception_container:
    image: probe_perception:latest
    container_name: perception_container
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    command: -c "source install/setup.bash && ros2 run probe_perception detect_probe.py"
    
# services:
#   perception_container:
#     image: probe_perception:latest
#     container_name: perception_container
#     runtime: nvidia
#     privileged: true
#     network_mode: host
#     volumes:
#       - ../:/ros2_ws
#       - /tmp/.X11-unix:/tmp/.X11-unix
#     environment:
#       - DISPLAY=${DISPLAY}
#       - NVIDIA_VISIBLE_DEVICES=all
#       - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
#     devices:
#       - /dev/video0:/dev/video0
#     entrypoint: /bin/bash
#     stdin_open: true
#     tty: true
#     #command: -c "source /opt/ros/jazzy/setup.bash && cd /ros2_ws && colcon build --packages-select probe_perception interfaces --cmake-args -DBUILD_PROBE_PERCEPTION=ON && source /ros2_ws/install/setup.bash && ros2 run probe_perception detect_probe"