services:
  perception_container:
    image: probe_perception:latest
    container_name: perception_container
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    command: -c "source install/setup.bash && ros2 run probe_perception detect_probe.py"