flight_controller_interface:
  ros__parameters:
    # Controller Parameters
    controller:
      pid_gains:
        pitch:
          Kp: 0.25
          Ki: 0.0
          Kd: 0.1
        roll:
          Kp: 0.25
          Ki: 0.0
          Kd: 0.1
        yaw:
          Kp: 0.15
          Ki: 0.0
          Kd: 0.05
        thrust:
          Kp: 1.3
          Ki: 0.0
          Kd: 0.15
      ema:
        alpha: 0.15 # Exponential moving average factor for smoothing
      constraints:
        max_linear_velocity: 0.4 # Maximum linear velocity (m/s)
        max_angular_velocity: 0.5 # Maximum angular velocity (rad/s)

    # Safety Parameters
    safety:
      check_gcs_timeout: false          # Check for ground control station timeout
      check_position_timeout: false     # Check for position data timeout
      gcs_timeout_threshold: 1.0        # Timeout for ground control station input (seconds)
      position_timeout_threshold: 0.2   # Timeout for position data (seconds)
      safety_thrust_initial: -0.72      # Initial thrust for safety landing (negative for downward)
      safety_thrust_final: -0.66        # Final thrust for safety landing (negative for downward)
      safety_thrustdown_rate: 0.0       # Rate of thrust decrease during safety landing

    # Setup Parameters
    setup:
      lidar_offset: 0.177 # Lidar offset for zero height calibration (meters)